name: flake-check

on:
  pull_request:
    paths:
      - "flake.nix"
      - "flake.lock"

permissions:
  contents: read

jobs:
  nix-check:
    name: nix-check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: nix flake check
        run: nix flake check --no-build --print-build-logs --no-update-lock-file --no-update-lock-file
